#cp p_{T}^{t}_abs.pdf ~/docs/TOP-17-014/myDir/papers/TOP-17-014/trunk/fig_logo/diff_results/primary/absolute/parton/DiffXS_HypToppT_bnlo.pdf
#cp p_{T}^{t}_norm.pdf ~/docs/TOP-17-014/myDir/papers/TOP-17-014/trunk/fig_logo/diff_results/primary/normalized/parton/DiffXS_HypToppT_bnlo.pdf
#cp p_{T}^{#bar{t}}_norm.pdf ~/docs/TOP-17-014/myDir/papers/TOP-17-014/trunk/fig_logo/diff_results/primary/normalized/parton/DiffXS_HypAntiToppT_bnlo.pdf
#cp p_{T}^{#bar{t}}_abs.pdf ~/docs/TOP-17-014/myDir/papers/TOP-17-014/trunk/fig_logo/diff_results/primary/absolute/parton/DiffXS_HypAntiToppT_bnlo.pdf
#cp y_{t}_norm.pdf ~/docs/TOP-17-014/myDir/papers/TOP-17-014/trunk/fig_logo/diff_results/primary/normalized/parton/DiffXS_HypTopRapidity_bnlo.pdf
#cp y_{t}_abs.pdf ~/docs/TOP-17-014/myDir/papers/TOP-17-014/trunk/fig_logo/diff_results/primary/absolute/parton/DiffXS_HypTopRapidity_bnlo.pdf
#cp y_{#bar{t}}_norm.pdf ~/docs/TOP-17-014/myDir/papers/TOP-17-014/trunk/fig_logo/diff_results/primary/normalized/parton/DiffXS_HypAntiTopRapidity_bnlo.pdf
#cp y_{#bar{t}}_abs.pdf ~/docs/TOP-17-014/myDir/papers/TOP-17-014/trunk/fig_logo/diff_results/primary/absolute/parton/DiffXS_HypAntiTopRapidity_bnlo.pdf
#cp m_{tt}_norm.pdf ~/docs/TOP-17-014/myDir/papers/TOP-17-014/trunk/fig_logo/diff_results/primary/normalized/parton/DiffXS_HypTTBarMass_bnlo.pdf
#cp m_{tt}_abs.pdf ~/docs/TOP-17-014/myDir/papers/TOP-17-014/trunk/fig_logo/diff_results/primary/absolute/parton/DiffXS_HypTTBarMass_bnlo.pdf
#cp P^{tt}_{T}_norm.pdf ~/docs/TOP-17-014/myDir/papers/TOP-17-014/trunk/fig_logo/diff_results/primary/normalized/parton/DiffXS_HypTTBarpT_bnlo.pdf
#cp P^{tt}_{T}_abs.pdf ~/docs/TOP-17-014/myDir/papers/TOP-17-014/trunk/fig_logo/diff_results/primary/absolute/parton/DiffXS_HypTTBarpT_bnlo.pdf
#cp y_{tt}_norm.pdf ~/docs/TOP-17-014/myDir/papers/TOP-17-014/trunk/fig_logo/diff_results/primary/normalized/parton/DiffXS_HypTTBarRapidity_bnlo.pdf
#cp y_{tt}_abs.pdf ~/docs/TOP-17-014/myDir/papers/TOP-17-014/trunk/fig_logo/diff_results/primary/absolute/parton/DiffXS_HypTTBarRapidity_bnlo.pdf
#cp dytt_norm_.pdf  ~/docs/TOP-17-014/myDir/papers/TOP-17-014/trunk/fig_logo/diff_results/primary/normalized/parton/DiffXS_HypTTBarDeltaRapidity_bnlo.pdf
#cp dytt_abs_.pdf ~/docs/TOP-17-014/myDir/papers/TOP-17-014/trunk/fig_logo/diff_results/primary/absolute/parton/DiffXS_HypTTBarDeltaRapidity_bnlo.pdf
cp p_{T}^{t}_abs.pdf ~/docs/TOP-17-014/myDir/papers/TOP-17-014/trunk/fig_logo/diff_results/primary/absolute/parton/DiffXS_HypToppT_bnlo.pdf
cp p_{T}^{t}_norm.pdf ~/docs/TOP-17-014/myDir/papers/TOP-17-014/trunk/fig_logo/diff_results/primary/normalized/parton/DiffXS_HypToppT_bnlo.pdf
cp p_{T}^{#bar{t}}_norm.pdf ~/docs/TOP-17-014/myDir/papers/TOP-17-014/trunk/fig_logo/diff_results/primary/normalized/parton/DiffXS_HypAntiToppT_bnlo.pdf
cp p_{T}^{#bar{t}}_abs.pdf ~/docs/TOP-17-014/myDir/papers/TOP-17-014/trunk/fig_logo/diff_results/primary/absolute/parton/DiffXS_HypAntiToppT_bnlo.pdf
cp y_{t}_norm.pdf ~/docs/TOP-17-014/myDir/papers/TOP-17-014/trunk/fig_logo/diff_results/primary/normalized/parton/DiffXS_HypTopRapidity_bnlo.pdf
cp y_{t}_abs.pdf ~/docs/TOP-17-014/myDir/papers/TOP-17-014/trunk/fig_logo/diff_results/primary/absolute/parton/DiffXS_HypTopRapidity_bnlo.pdf
cp y_{#bar{t}}_norm.pdf ~/docs/TOP-17-014/myDir/papers/TOP-17-014/trunk/fig_logo/diff_results/primary/normalized/parton/DiffXS_HypAntiTopRapidity_bnlo.pdf
cp y_{#bar{t}}_abs.pdf ~/docs/TOP-17-014/myDir/papers/TOP-17-014/trunk/fig_logo/diff_results/primary/absolute/parton/DiffXS_HypAntiTopRapidity_bnlo.pdf
cp m_{t#bar{t}}_norm.pdf ~/docs/TOP-17-014/myDir/papers/TOP-17-014/trunk/fig_logo/diff_results/primary/normalized/parton/DiffXS_HypTTBarMass_bnlo.pdf
cp m_{t#bar{t}}_abs.pdf ~/docs/TOP-17-014/myDir/papers/TOP-17-014/trunk/fig_logo/diff_results/primary/absolute/parton/DiffXS_HypTTBarMass_bnlo.pdf
cp p^{t#bar{t}}_{T}_norm.pdf ~/docs/TOP-17-014/myDir/papers/TOP-17-014/trunk/fig_logo/diff_results/primary/normalized/parton/DiffXS_HypTTBarpT_bnlo.pdf
cp p^{t#bar{t}}_{T}_abs.pdf ~/docs/TOP-17-014/myDir/papers/TOP-17-014/trunk/fig_logo/diff_results/primary/absolute/parton/DiffXS_HypTTBarpT_bnlo.pdf
cp y_{t#bar{t}}_norm.pdf ~/docs/TOP-17-014/myDir/papers/TOP-17-014/trunk/fig_logo/diff_results/primary/normalized/parton/DiffXS_HypTTBarRapidity_bnlo.pdf
cp y_{t#bar{t}}_abs.pdf ~/docs/TOP-17-014/myDir/papers/TOP-17-014/trunk/fig_logo/diff_results/primary/absolute/parton/DiffXS_HypTTBarRapidity_bnlo.pdf
cp dytt_nn.pdf  ~/docs/TOP-17-014/myDir/papers/TOP-17-014/trunk/fig_logo/diff_results/primary/normalized/parton/DiffXS_HypTTBarDeltaRapidity_bnlo.pdf
cp dytt_aa.pdf ~/docs/TOP-17-014/myDir/papers/TOP-17-014/trunk/fig_logo/diff_results/primary/absolute/parton/DiffXS_HypTTBarDeltaRapidity_bnlo.pdf
